USER_ID = "Ribura"
API_PATH = "https://kenkoooo.com/atcoder/atcoder-api/results?user="
REPOSITORY_URL = "git@github.com:m-star18/atcoder.git"
ROOT = "submissions/"
PROJECT_PATH = "/home/m-star18/PycharmProjects/atcoder/"
